language: python
python:
  - "2.7"
  - "pypy"
install:
  - pip install pybuilder
  - pip install coveralls
  - pyb install_dependencies

script: "pyb verify analyze"
after_success:
  - coveralls --verbose

